[project]
name = "cunny"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "customtkinter>=5.2.0",
    "google-generativeai>=0.3.0",
    "keras>=2.13.0",
    "matplotlib>=3.7.0",
    "mediapipe>=0.10.0 ; python_full_version < '3.13'",
    "mss>=9.0.0",
    "numpy>=1.24.0",
    "opencv-python>=4.8.0",
    "openpyxl>=3.1.0",
    "pandas==2.2.2",
    "pillow>=10.0.0",
    "pyaudio>=0.2.14 ; python_full_version < '3.13'",
    "pygame>=2.5.0",
    "pyttsx3>=2.90",
    "requests>=2.31.0",
    "speechrecognition>=3.10.0",
    "tensorflow>=2.13.0",
]
